// Copyright (c) 2026 Fluxo Labs
// AI-generated code based on idea by alisio85
// SPDX-License-Identifier: MIT

//! State trait and types for Fluxo Typestate.
//!
//! This module provides the core traits that form the foundation of the type-state
//! pattern in Fluxo. It includes the `State` trait that all state types must
//! implement, and the `Sealed` trait that prevents external implementations.
//!
//! # The Type-State Pattern
//!
//! The type-state pattern is a design pattern in Rust where each distinct state
//! is represented by a different type. This allows the compiler to enforce at
//! compile-time that:
//!
//! 1. Objects can only be in valid states
//! 2. State transitions can only happen through defined paths
//! 3. Methods that depend on state are only available in appropriate states
//!
//! ## Example
//!
//! Without type-state, you might have:
//!
//! ```ignore
//! struct Computer {
//!     state: State,
//!     cpu_load: f32,
//! }
//!
//! enum State { Idle, Running, Sleeping }
//!
//! impl Computer {
//!     fn start(&mut self) -> Result<(), &str> {
//!         if self.state != State::Idle {
//!             return Err("Can only start from idle");
//!         }
//!         self.state = State::Running;
//!         self.cpu_load = 0.0;
//!         Ok(())
//!     }
//! }
//! ```
//!
//! With type-state (and Fluxo), you get compile-time guarantees:
//!
//! ```ignore
//! #[state_machine]
//! enum Computer {
//!     Idle,
//!     Running { cpu_load: f32 },
//!     Sleeping,
//! }
//!
//! // This won't compile - can't call start() on Sleeping!
//! let sleeping: Computer<Sleeping> = /* ... */;
//! let running = sleeping.start(); // COMPILE ERROR!
//! ```
//!
//! # How It Works
//!
//! 1. You define your states as enum variants
//! 2. Fluxo generates a struct for each variant
//! 3. The main wrapper type is generic over the state: `Computer<S>`
//! 4. Methods are only available when the type parameter matches
//! 5. Transition methods consume `self` and return the new state type
//!
//! # State Trait
//!
//! The `State` trait is the core trait that all state types must implement.
//! It provides a single method `name()` that returns a static string
//! representing the state type name.
//!
//! The macro automatically implements this trait for each generated state struct.
//!
//! # Sealed Trait
//!
//! The `Sealed` trait is used to prevent external crates from implementing the
//! `State` trait. This is crucial for maintaining the type safety guarantees
//! of the pattern. If anyone could implement `State`, they could create states
//! that bypass the compile-time checks.
//!
//! The `Sealed` trait requires `Clone + Send + Sync + 'static` to ensure
//! states are well-behaved and can be used safely in concurrent contexts.

// Copyright (c) 2026 Fluxo Labs
// AI-generated code based on idea by alisio85
// SPDX-License-Identifier: MIT

/// The core trait implemented by all state types in the type-state pattern.
///
/// This trait represents a single state in a state machine. Every state type
/// generated by the `#[state_machine]` macro automatically implements this trait.
///
/// # Purpose
///
/// The `State` trait serves two main purposes:
///
/// 1. **Type Marker**: It acts as a marker trait that identifies types as valid
///    states in a state machine.
///
/// 2. **Introspection**: The `name()` method allows runtime debugging by providing
///    a human-readable name for each state type.
///
/// # Implementation
///
/// **You should not implement this trait manually.** The `#[state_machine]` macro
/// automatically generates implementations for all state structs. Manual implementation
/// is prevented by the `Sealed` trait bound.
///
/// # Example
///
/// When you write:
///
/// ```ignore
/// #[state_machine]
/// enum Computer {
///     Idle,
///     Running { cpu_load: f32 },
/// }
/// ```
///
/// The macro generates:
///
/// ```ignore
/// pub struct Idle;
/// pub struct Running { pub _0: f32 }
///
/// impl fluxo_typestate::State for Idle {
///     fn name(&self) -> &'static str {
///         "Idle"
///     }
/// }
///
/// impl fluxo_typestate::State for Running {
///     fn name(&self) -> &'static str {
///         "Running"
///     }
/// }
/// ```
///
/// # Method
///
/// - `name(&self) -> &'static str`: Returns the name of the state type as a
///   static string slice. This is typically the struct name generated from
///   the enum variant name.
pub trait State: Sealed + 'static {
    /// Returns the name of this state as a static string.
    ///
    /// This method provides a way to get a human-readable representation
    /// of the current state type, useful for debugging and logging.
    ///
    /// # Returns
    ///
    /// A static string slice containing the state's name (typically the
    /// struct name generated from the enum variant).
    ///
    /// # Example
    ///
    /// ```ignore
    /// let idle = Idle;
    /// assert_eq!(idle.name(), "Idle");
    /// ```
    fn name(&self) -> &'static str;
}

/// A sealed trait that prevents external implementations of `State`.
///
/// The `Sealed` trait is a marker trait that, when combined with the `State`
/// trait, prevents downstream crates from implementing `State` for their own
/// types. This is essential for maintaining the type safety guarantees of
/// the type-state pattern.
///
/// # Why Seal the Trait?
///
/// Without sealing, anyone could implement `State` for arbitrary types:
///
/// ```ignore
/// // This would break type safety!
/// struct InvalidState;
/// impl State for InvalidState { fn name(&self) -> &str { "Invalid" } }
/// ```
///
/// By sealing the trait, we ensure that only the `#[state_machine]` macro
/// (which has access to internal implementation details) can create valid
/// state types.
///
/// # Requirements
///
/// All sealed types must be:
/// - `Clone`: Enable state cloning when needed
/// - `Send`: Enable safe transfer between threads
/// - `Sync`: Enable safe sharing between threads
/// - `'static`: Ensure the type has no lifetime dependencies
///
/// These requirements ensure states can be used safely in concurrent and
/// static contexts.
pub trait Sealed: Clone + Send + Sync + 'static {}
